# Generated by Django 4.1 on 2022-09-05 18:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('careerapp', '0002_instructor_course_album'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='author',
            new_name='instructor',
        ),
    ]
