# Generated by Django 4.1 on 2022-09-06 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('careerapp', '0005_alter_user_major'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='instructor',
        ),
        migrations.AlterField(
            model_name='course',
            name='field',
            field=models.CharField(choices=[('web development', 'Web Development'), ('android development', 'Android Development'), ('ios development', 'IOS Development'), ('graphics design', 'Graphics Design'), ('digital marketing', 'Digital Marketing'), ('quality assurance', 'Quality Assurance'), ('database design', 'Database Design'), ('machine learning', 'Machine Learning')], max_length=50),
        ),
    ]
